# Generated by Django 4.1.2 on 2023-03-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.CharField(default=0, max_length=330),
        ),
    ]
